simplified constructors declaration, started adding Indexer
Got a weird compilation error:

/Users/gubatron/workspace.frostwire/yuca/swig/yuca_java_wrap.cxx:1420:38: error: object of type
      'yuca::utils::Map<std::__1::basic_string<char>, yuca::utils::List<std::__1::basic_string<char> > >' cannot be
      assigned because its copy assignment operator is implicitly deleted
  if (arg1) (arg1)->tag_keywords_map = *arg2;
                                     ^
/Users/gubatron/workspace.frostwire/yuca/src/yuca/utils.hpp:376:21: note: copy assignment operator of
      'Map<std::__1::basic_string<char>, yuca::utils::List<std::__1::basic_string<char> > >' is implicitly deleted
      because field 'default_empty_value' has no copy assignment operator
            const V default_empty_value;
                    ^
1 error generated.
: